added support for polygon bboxes
v7labs/darwin-py pull request #271
Opened 2021-11-10 13:34 UTC by Fl4m3Ph03n1x

2021-11-10 17:13 UTC, andreaazzini requested changes

2021-11-11 09:44 UTC, FrancescoSaverioZuppichini commented on darwin/exporter/formats/pascalvoc.py
> +            add_subelement_text(bndbox, "ymax", str(round(ymax)))
question: why do we need to round the coordinates?

2021-11-11 09:48 UTC, andreaazzini commented on darwin/exporter/formats/pascalvoc.py
> +            add_subelement_text(bndbox, "ymax", str(round(ymax)))
I think because AFAIK Pascal VOC requires those fields to be integers

2021-11-11 10:16 UTC, Fl4m3Ph03n1x commented on darwin/exporter/formats/pascalvoc.py
> +            add_subelement_text(bndbox, "ymax", str(round(ymax)))
Done !

2021-11-11 11:37 UTC, Fl4m3Ph03n1x commented on darwin/exporter/formats/pascalvoc.py
> +        if annotation_type not in ["bounding_box", "polygon"]:
done !

2021-11-11 14:44 UTC, andreaazzini approved these changes

2021-11-11 15:30 UTC, merged