[V7-2846] Add ndpi support
v7labs/darwin-py pull request #338
Opened 2022-02-04 12:57 UTC by simedw

2022-02-04 12:59 UTC, Fl4m3Ph03n1x commented
I have no idea what `ndpi` nor what is used for. 
Based on the code I guess it is some kind of video. 

Looks good to me.

2022-02-04 13:00 UTC, Fl4m3Ph03n1x approved these changes
If it passes the pipeline, its good to go.

2022-02-04 13:19 UTC, andreaazzini approved these changes

2022-02-04 13:32 UTC, Fl4m3Ph03n1x commented
Cannot merge until pipeline is fixed.

2022-02-07 10:35 UTC, andreaazzini requested changes

2022-02-07 10:35 UTC, andreaazzini commented on darwin/dataset/split_manager.py
> +        print(error)
Is this expected?

2022-02-07 10:45 UTC, simedw commented on darwin/dataset/split_manager.py
> +        print(error)
this is pedro debugging the issue

2022-02-07 11:03 UTC, Fl4m3Ph03n1x approved these changes

2022-02-07 11:16 UTC, andreaazzini approved these changes

2022-02-07 13:41 UTC, merged