Addes --yes flag to skip primpts when importing
v7labs/darwin-py pull request #360
Opened 2022-02-24 14:30 UTC by simedw

2022-02-24 15:52 UTC, andreaazzini requested changes
It works, just tested it!

Blocking this because tests are missing, @simedw is this urgent to release?

2022-02-24 16:43 UTC, Fl4m3Ph03n1x commented
Wait, shouldn't the default behavior be: "We prompt the user?"

I just imported some annotations (the classes were deleted beforehand) and I was not asked for confirmation:

```
$ darwin dataset import cars darwin /home/pedro/Downloads/annotations/
Fetching remote class list...
Retrieving local annotations ...
Fetching remote file list...
3 annotation file(s) found.
3 classes needs to be created.
0 classes needs to be added to andreas-team/cars
About to create the following classes
        car_bbox, type: bounding_box
        car, type: polygon
        car_ellipse, type: ellipse
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
```

2022-02-25 10:56 UTC, andreaazzini requested changes

2022-02-25 10:56 UTC, andreaazzini commented on darwin/cli.py
> +            f.dataset_import(args.dataset, args.format, args.files, args.append, args.yes)
Blocked for another reason:
```suggestion
            f.dataset_import(args.dataset, args.format, args.files, args.append, not args.yes)
```

In the other functions, we're using `class_prompt` as a flag that is `True` when `--yes` is `False`!

Luckily caught that today, when using this branch to upload data with classes which did not exist! Yesterday everything went fine as classes existed in the team, but not in the dataset, and were automatically added

2022-02-25 15:15 UTC, andreaazzini approved these changes

2022-02-25 15:18 UTC, merged