Reduce API surface. Improved docs.
v7labs/darwin-py pull request #373
Opened 2022-03-21 12:18 UTC by Fl4m3Ph03n1x

2022-03-23 10:25 UTC, tomvars commented on darwin/importer/importer.py
> +    return f"`{local_cls_name}` class of type `{local_annotation_type}` from imported annotations clashes with an existing class of the same name; but of type `{existing_type}`"
This line is too long

2022-04-05 07:37 UTC, andreaazzini requested changes
We are deprecating functions that are going to be turned into private ones, but we don't introduce their private counterparts here. Is that intended?

2022-04-05 11:51 UTC, Fl4m3Ph03n1x commented
Yes, for the time being, it is intended.

2022-04-05 12:40 UTC, andreaazzini approved these changes
Approving, since when we remove those functions it will be obvious we'll have to add the private functions

2022-04-05 12:41 UTC, merged