python 3.11 support
v7labs/darwin-py pull request #651
Opened 2023-08-24 08:25 UTC by Nathanjp91

# Problem
darwin-py doesn't support python 3.11

# Solution
Change dependencies to allow 3.11 support

# Changelog
Python 3.11 support added. Python 3.7 support dropped

2023-08-24 09:03 UTC, owencjones submitted a review, later dismissed
LGTM, some offline discussion to be had in house

2023-08-24 09:17 UTC, owencjones requested changes
I think remove `pyproject.toml:L69`, or at least consider it and respond. 🙂

2023-08-24 09:17 UTC, owencjones commented on pyproject.toml
>  deprecation = "^2.1.0"
Due to [Github limitation](https://github.com/orgs/community/discussions/4452) I can't comment on the exact line I need to, but on `L69` can be entirely removed now, as it's only needed by Python 3.7

Arguably, we could keep it for people who forcibly install on 3.7, but I think I err on the side of not doing personally, especially given that you've changed other python version dependant installs.

2023-08-24 09:31 UTC, owencjones approved these changes

2023-11-15 15:39 UTC, closed without merging

2023-11-15 15:39 UTC, Nathanjp91 commented
Working via this PR instead
https://github.com/v7labs/darwin-py/pull/692