Ai 1190 implement and test augmentations
v7labs/darwin-py pull request #665
Opened 2023-09-22 12:17 UTC by ChristofferEdlund

# Problem
We want to introduce the possibility to use Albumentation transforms with darwin-py torch datasets. 

# Solution
Introducing an `AlbumentationsTransform` class in torch.transforms that can be be used in the following manner:

```
from darwin.torch.dataset import (
    ClassificationDataset,
    InstanceSegmentationDataset,
    ObjectDetectionDataset,
    SemanticSegmentationDataset,
)

from darwin.torch.transforms import AlbumentationsTransform

dataset_path = Path(r"/path/to/local/darwin/dataset")
transform = AlbumentationsTransform.from_path('/tmp/transform.json')

inst_dataset = InstanceSegmentationDataset(dataset_path=dataset_path, transform=transform)
```
One can initilize the `AlbumentationsTransform` in three ways:
- AlbumentationsTransform(albumentation_transform) <- needs an albumentations transformation
- AlbumentationsTransform.frompath(path) <- a path pointing to a .json or .yaml file defining the transformation
- AlbumentationsTransform.fromdict(dict) <- a dictionary defining the transform

To read more about the dictionary and file formats supported, we refer to the [albumentations documentation.](https://albumentations.ai/docs/examples/serialization/#Serializing-an-augmentation-pipeline-to-a-JSON-or-YAML-file)

Further.
- Instance segmentation dataset output is changed for bounding boxes to be `coco` format (X, Y, W, H) to be consistent with darwin-json annotations and the ObjectDetecion torch dataset.
- Clamping is introduced to ObjectDetection bboxes that is outside of image for more robust data loading.

# Changelog
- Introduced albumentation transform support for darwin torch datasts
- darwin.torch.dataset.InstanceSegmentationDataset has bbox coordinates changes from `pascal_voc` to `coco` format (X, Y, H, W)
- darwin.torch.dataset.ObjectDetectionDataset clamps bbox coordinates out-of-bound.

2023-09-22 16:07 UTC, dorfmanrobert commented on darwin/torch/transforms.py
> +        # keep = (boxes[:, 3] > boxes[:, 1]) & (boxes[:, 2] > boxes[:, 0])
can remove commented out lines

2023-09-26 09:05 UTC, owencjones commented
Updated title so that it's easier for me on deployment 😉

2023-09-27 16:41 UTC, almazan approved these changes
All changes look good to me.

2023-09-27 16:47 UTC, almazan requested changes
Some comments need to be addressed before approval

2023-09-27 16:54 UTC, almazan requested changes

2023-09-27 16:54 UTC, almazan commented on darwin/torch/transforms.py
> -            keypoints = keypoints[keep]
I believe this logic was added for cases with bboxes of either width or height of size 0px. Should we add it back? The easiest way to add it back is to compute `keep` using a `tmp_boxes` converted to `x,y,x,y` using `tmp_boxes[:, 2:] += boxes[:, :2]` and then filter `boxes` using `keep`.

2023-09-27 18:23 UTC, almazan commented on darwin/torch/transforms.py
>          boxes[:, 1::2].clamp_(min=0, max=h)
This is not clamping bboxes anymore, since now indexes 2 and 3 are height and width instead of x2 and y2. Boxes now could go outside of the image.

2023-09-28 14:10 UTC, almazan approved these changes

2023-09-28 14:23 UTC, merged