[AI-1245] added albumentations transform test
v7labs/darwin-py pull request #672
Opened 2023-09-29 11:25 UTC by ChristofferEdlund

# Problem
No pytests for the new albumentations transform in darwin-py transforms

# Solution
Added a pytest

# Changelog
- Pytest added for albumentations transform

2023-09-29 13:16 UTC, ChristofferEdlund reviewed
Perhaps we do not want to deploy this "quck-fix" to master? Not sure why albumentations are not installed otherwise..

2023-09-29 13:17 UTC, ChristofferEdlund commented on .github/workflows/tests.yml
> +          pip install albumentations
Perhaps we do not want to deploy this "quck-fix" to master? Not sure why albumentations are not installed otherwise..

2023-10-01 16:04 UTC, owencjones requested changes
One change requested, also reach out on slack to sort the issue with albumentations

2023-10-01 16:04 UTC, owencjones commented on tests/darwin/torch/transform_test.py
> +        assert annotation["iscrowd"] == SAMPLE_ANNOTATION["iscrowd"]
Could you add an if main style statement to the bottom of this for concurrency purposes?

```python

if name == "__main__":
    pytest.run()
```

2023-10-13 12:21 UTC, ChristofferEdlund commented on .github/workflows/tests.yml
> +          pip install albumentations
That worked great,thanks!

2023-10-13 15:45 UTC, owencjones approved these changes
Looks good, good test coverage with happy and sad paths

2023-10-16 11:23 UTC, owencjones approved these changes
Yeah, all looking good.  Ready for QA.

2023-10-16 11:23 UTC, owencjones commented on .vscode/settings.json
>    "python.formatting.blackArgs": [
Removing these lines below on here will mean that formatOnSave starts working better

2023-10-16 11:33 UTC, merged