[MED-22][external] import nifti to raster layer mask annotations
v7labs/darwin-py pull request #725
Opened 2023-11-21 13:22 UTC by tomvars

# Problem
We previously supported nifti imports as polygons, this PR introduces support for nifti imports into the raster layer.
# Solution
Users now have a new mode available at upload. In addition to `video` and `instances` which both write polygons into Darwin, users now have `mask` mode which writes to the raster layer and creates `mask` annotations.

# Changelog
We've introduced the ability to import nifti labels directly into the raster layer! This means users can perform inference off-platform or import existing annotations into a project and then annotate them using our Masks feature.

2023-12-13 14:26 UTC, Nathanjp91 requested changes
Would also love to see some tests added if possible.

2023-12-13 14:26 UTC, Nathanjp91 commented on darwin/importer/formats/nifti.py
> +def get_mask_video_annotations(volume, processed_class_map, slot_names):
Can you type annotate this? Inputs and outputs.

2023-12-13 14:26 UTC, Nathanjp91 commented on darwin/importer/formats/nifti.py
> +def nifti_to_video_polygon_annotation(
Same as above.

2023-12-13 14:26 UTC, Nathanjp91 commented on darwin/importer/formats/nifti.py
> +def convert_to_dense_rle(raster):
as above.

2023-12-15 15:29 UTC, tomvars commented
> Would also love to see some tests added if possible.

Added a test

2023-12-19 11:29 UTC, Nathanjp91 approved these changes

2023-12-19 11:29 UTC, Nathanjp91 commented on tests/darwin/importer/formats/import_nifti_test.py
> +import ast
I'm guessing this a stray import from vscode? if so remove it
```suggestion
```

2023-12-19 11:47 UTC, merged